apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internships-portal
  title: Internships Portal
  description: A website for managing interns & internships.
  annotations:
    github.com/project-slug: Staffing-HQ/internships-portal
    backstage.io/techdocs-ref: dir:.
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
    sonarqube.org/project-key: Staffing-HQ/interships-portal
  tags:
    - internships
    - interns
spec:
  type: website
  lifecycle: experimental
  owner: group:default/internship
  system: internships-system
  dependsOn: ['api:internships-srv-api']
